[package]
name = "alternative_vrs"
version = "0.2.0"
edition = "2021"

[dependencies]
csv = "1.3.1"
rand = "0.9.0"
serde = {version = "1.0.217", features = ["derive"]}
serde-aux = "4.5.0"
serde_json = "1.0.134"
